field: e048ca5f-31cb-4590-8e66-909863f27a7f # Recipe Contents
fieldLayouts:
  afe41a21-55ea-4165-b73a-0f5b82d18934:
    tabs:
      -
        elements:
          -
            fieldUid: 197e9178-b905-4873-be42-264a8f52a562 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c99a2d3e-2be7-47a5-a496-7d13954b4606 # Image Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  197e9178-b905-4873-be42-264a8f52a562: # Image
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:f0b37a25-fb80-4ee9-9f5e-bd345161ed33' # Drinks
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:f0b37a25-fb80-4ee9-9f5e-bd345161ed33' # Drinks
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  c99a2d3e-2be7-47a5-a496-7d13954b4606: # Image Caption
    contentColumnType: text
    fieldGroup: null
    handle: imageCaption
    instructions: ''
    name: 'Image Caption'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: recipeImage
name: 'Recipe Image'
sortOrder: 1
