fieldLayouts:
  355ae893-d09c-4053-b67a-d4f0626eb118:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: ''
            label: 'Recipe Name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: af87d995-8e70-4db0-98f6-016a7b13982a # Drink Style
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e048ca5f-31cb-4590-8e66-909863f27a7f # Recipe Contents
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: recipes
hasTitleField: true
name: Recipes
section: e1707bb6-dc83-476e-839e-a96de6110325 # Recipes
sortOrder: 1
titleFormat: 'Recipe Name'
titleTranslationKeyFormat: null
titleTranslationMethod: site
