enableVersioning: true
handle: drinks
name: Drinks
propagationMethod: all
siteSettings:
  a2bc7469-9fb9-4628-911d-d3676984705f: # Crafty Coffee
    enabledByDefault: true
    hasUrls: true
    template: drinks/_entry
    uriFormat: 'drinks/{slug}'
type: channel
