enableVersioning: true
handle: homepage
name: Homepage
propagationMethod: all
siteSettings:
  a2bc7469-9fb9-4628-911d-d3676984705f: # Crafty Coffee
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
