enableVersioning: true
handle: news
name: News
propagationMethod: all
siteSettings:
  a2bc7469-9fb9-4628-911d-d3676984705f: # Crafty Coffee
    enabledByDefault: true
    hasUrls: true
    template: news/_entry
    uriFormat: 'news/{slug}'
type: channel
